import ModelSNav from "./components/ModelSNav";

export const metadata = {
  title: "Model S | Tesla",
  description: "Generated by create next app",
};
export default function Layout({ children }) {
  return <main>
    <ModelSNav />
    {children}
    </main>;
}
