import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Alert from '@/components/Alert'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Tesla',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Alert />
        <Navbar />
        {children}
      </body>
    </html>
  )
}
