
import ModelXNav from "./components/ModelXNav";
export const metadata = {
  title: "Model X | Tesla",
  description: "Generated by create next app",
};
export default function Layout({ children }) {
  return <main>
    <ModelXNav />
    {children}
    </main>;
}
